server:
  port: 7002
spring:
  application:
    name: eurekaService
eureka:
  instance:
    # hostname 是用来表示主机的,appname是用来表示分组的
    hostname: eureka2.com #eureka服务端的实例名称
    # 两个eureka 相互进行服务列表同步,保证一致性,如果其中一个挂了,可以继续使用另外一个
  client:
    #是否将自己注册到Eureka Server,默认为true，由于当前就是server，故而设置成false，表明该服务不会向eureka注册自己的信息
    register-with-eureka: true
    #是否从eureka server获取注册信息，由于单节点，不需要同步其他节点数据，用false
    fetch-registry: true
    service-url:
      # 往eureka1注册
      defaultZone: http://eureka1.com:7001/eureka/