server:
  port: 7001
spring:
  application:
    name: eurekaService
eureka:
  instance:
    # hostname 是用来表示主机的,appname是用来表示分组的
    hostname: eureka1.com #eureka服务端的实例名称
  client:
    #是否将自己注册到Eureka Server,默认为true，由于当前就是server，故而设置成false，表明该服务不会向eureka注册自己的信息
    register-with-eureka: true
    #是否从eureka server获取注册信息，由于单节点，不需要同步其他节点数据，用false
    fetch-registry: true
    service-url:
      # 往eureka2注册
      defaultZone: http://eureka2.com:7002/eureka/