# ---------------微服务相关---------------------------
spring:
  # applicaton name 实际上表示的是一个组
  application:
    name: eureka-client-provider
#-------------服务端口--------------------------------
server:
  port: 8003
  # 服务端开启压缩(接口请求过来的时候进行压缩)
  compression:
    enabled: true
#----------开启所有监控端点和actuator有关系--------------
management:
  endpoints:
    web:
      exposure:
        include: "*"
  #开启远程关闭功能,可以实现远程对这个服务节点下线控制
  endpoint:
    shutdown:
      enabled: true
#------------注册中心相关-------------------------------
eureka:
  client:
    #此客户端是否获取eureka服务器注册表上的注册信息，默认为true
    # 拉取注册地中心的服务列表
    fetch-registry: true
    #实例是否在eureka服务器上注册自己的信息以供其他服务发现，默认为true,即自己注册自己。
    # 将自身服务注册到注册中心中,给其他服务进行调用
    register-with-eureka: true
    service-url:
      #defaultZone 这个是不会提示的，此处需要自己写
      #实际上属性应该是service-url,这个属性是个map（key-value）格式；当key是defaultZone的时候才能被解析；所以这里没有提示，
      #但是自己还需要写一个defaultZone；
      defaultZone: http://eureka1.com:7001/eureka
  #服务注册中心实例的主机名
  # instance 表示的是一个服务
  instance:
    hostname: provider
    prefer-ip-address: false
    instance-id: provider-8003